version: '3.9'

services:
  api:
    build: .
    container_name: event-contract-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/var/log/nest
       
    command: npm run start:dev
    restart: always

  db:
    image: postgres:15
    container_name: event-contract-postgres-db
    ports:
      - "4432:5432"               
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
