version: '3.9'

services:
  api:
    build: .
    container_name: event-contract-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/var/log/nest
       
    command: npm run start:dev
    restart: always

  db:
    image: postgres:15
    container_name: event-contract-postgres-db
    ports:
      - "4432:5432"               
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  web:
    build: ./web
    container_name: event-contract-web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
    volumes:
      - ./web:/app
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - api
    restart: always

volumes:
  postgres-data:
